name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x64, arm64]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install FUSE (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libfuse-dev

      - name: Setup Homebrew (macOS)
        if: matrix.os == 'macos-latest' && env.ACT != 'true'
        run: |
          if ! command -v brew &> /dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi
          brew update

      - name: Install FUSE (macOS)
        if: matrix.os == 'macos-latest' && env.ACT != 'true'
        run: |
          # brew uninstall --cask macfuse || true
          # brew install --cask macfuse@dev

      - name: Setup Bun
        if: matrix.os != 'macos-latest' || env.ACT != 'true'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      # Test step (runs everywhere)
      - name: Run tests
        run: bun run test
